### ISSUE TITLE
python gtest_parallel.py --help doesn't do anything

### ISSUE THREAD

**Issue by ftrofin** [google/gtest-parallel#56]
This looks like a very useful utility but unfortunately I could not get it to work. I cloned the code and tried invoking the script both via 'python gtest_parallel.py` and via the script and nothing happens : no output, no error, nothing. I tried with and without arguments, same results. I tried this on a Mac (10.12.6) with Python 2.7.10 and Windows 10 with Ptyhon 2.7.8.

**Comment by pbos** [comment]
You should be running `python gtest-parallel` and not `gtest_parallel.py`. To be fair though, I think running `gtest_parallel.py` should be equivalent.
