### ISSUE TITLE
Missing year and name of copyright owner in LICENSE file.

### ISSUE THREAD

**Issue by kshithijiyer** [google/gtest-parallel#68]
Apache License V2.0 requires the LICENSE to have the year and name of the copyright owner. The values are present in LICENSE file and have to be edited when applied to the projects as state in the LICENSE as shown below. I think it was missed for this project. 
`Copyright [yyyy] [name of copyright owner]` has to be changed to `Copyright 2013 Google Inc.`.

**Comment by kshithijiyer** [comment]
Fix submitted: d9e4e36

**Comment by pbos** [comment]
Hi, I checked with our open-source team, they pointed out that this section of the `LICENSE` file is boilerplate suggestions for other folks who wish to apply the license to their own work, not something that's intended to be replaced in this copy of the LICENSE file.

It's under:

   APPENDIX: How to apply the Apache License to your work.

Some version of this boilerplate is already present in the source files.

**Comment by kshithijiyer** [comment]
Hi! I am extremely sorry for this confusion.

**Comment by pbos** [comment]
No problem, thanks for checking in. :)
